package com.android.sitbak.network

object ApiTags {

    const val REGISTER = "Register"
    const val LOGIN = "Login"
    const val EMAIL_PHONE_CONFIRMATION = "EmailPhoneConfirmation"
    const val RESEND_OTP = "ResendOtp"
    const val ADD_UPDATE_PHOTO = "AddUpdatePhoto"
    const val ADD_UPDATE_PHONE = "AddUpdatePhone"
    const val RECOVER_BY_EMAIL = "RecoverByEmail"
    const val RECOVER_BY_PHONE = "RecoverByPhone"
    const val RESET_PASSWORD = "ResetPassword"
    const val CHANGE_PASSWORD = "ChangePassword"
    const val LOGOUT = "Logout"
    const val GET_PROFILE = "GetProfile"
    const val UPDATE_PROFILE = "UpdateProfile"
    const val UPDATE_EMAIL = "UpdateEmail"
    const val GET_AVAILABLE_TICKETS = "GetAvailableTickets"
    const val GET_PROCESSING_TICKETS = "GetProcessingTickets"
    const val ACCEPT_ORDER = "acceptOrder"
    const val CANCEL_DELIVERY = "cancelDelivery"
    const val SEND_CHAT = "SendChat"
    const val GET_CHAT = "GetChat"
    const val GET_YOUR_EARNINGS = "GetYourEarnings"
    const val START_DELIVERY = "StartDelivery"
    const val COMPLETE_DELIVERY = "CompleteDelivery"
    const val GET_REGION = "GetRegion"
    const val GET_MY_SHIFTS = "GetMyShifts"
    const val GET_OPEN_SHIFTS = "GetOpenShifts"
    const val ADD_OPEN_SHIFTS = "AddOpenShifts"
    const val GET_AVAILABILITIES = "GetAvailabilities"
    const val ADD_AVAILABILITY = "AddAvailability"
    const val UPDATE_AVAILABILITY = "UpdateAvailability"
    const val SWITCH_AVAILABILITY = "SwitchAvailability"
    const val DELETE_SHIFTS = "DeleteShifts"
    const val GET_COMPLETED_SHIFTS = "GetCompletedShifts"
    const val GET_ARCHIVE_SALARY = "GetArchiveSalary"
    const val GET_MONEY = "GetMoney"

}